/** Welcome / empty-desk sample document. */
export const SAMPLE = [
  '# Writing Desk',
  '',
  'Write straight onto this page — the toolbar above works the way you',
  'expect. Underneath it stays plain Markdown, which you can read and edit',
  'from the Markdown view. One file, no dependencies, no network requests.',
  '',
  '## What it understands',
  '',
  'Headings, **strong**, *emphasis*, ~~strikethrough~~, `inline code`, and',
  'links like [the CommonMark spec](https://commonmark.org). Two spaces at',
  'the end of a line  ',
  'make a hard break.',
  '',
  '> Quotes nest, and can contain anything else.',
  '>',
  '> — including other blocks',
  '',
  '### Lists',
  '',
  '- Unordered, with nesting',
  '  - and a second level',
  '- [x] Task lists work',
  '- [ ] Even unfinished ones',
  '',
  '1. Ordered lists too',
  '2. Numbered from wherever you start',
  '',
  '### Tables',
  '',
  '| Feature | Supported | Note |',
  '| --- | :---: | --- |',
  '| Tables | yes | with alignment |',
  '| Raw HTML | no | escaped on purpose |',
  '',
  '### Code',
  '',
  '```js',
  'const words = text.match(/[\\p{L}\\p{N}]+/gu);',
  'console.log(words.length);',
  '```',
  '',
  '---',
  '',
  'Everything you type is saved in this browser only. Export as Markdown or',
  'as a standalone HTML file, or print it to PDF.',
  ''
].join('\n');
